export const SAVE_MARKERS_REQUEST = 'SAVE_MARKERS_REQUEST';
export const SAVE_MARKERS_SUCCESS = 'SAVE_MARKERS_REQUEST';
export const SAVE_MARKERS_FAIL = 'SAVE_MARKERS_REQUEST';
export const GET_MARKERS_REQUEST = 'GET_MARKERS_REQUEST';
export const GET_MARKERS_SUCCESS = 'GET_MARKERS_SUCCESS';
export const GET_MARKERS_FAIL = 'GET_MARKERS_REQUEST';